steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kunal-ica1/text-generator:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kunal-ica1/text-generator:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['kubectl', 'apply', '-f', 'k8s/deployment.yaml']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['kubectl', 'apply', '-f', 'k8s/service.yaml']
images:
  - 'gcr.io/kunal-ica1/text-generator:latest'
options:
  logging: CLOUD_LOGGING_ONLY