steps:
  # Step 1: Check if the cluster exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud container clusters describe my-cluster --zone us-central1-a --project kunal-ica1; then
          echo "Cluster does not exist. Creating cluster."
          gcloud container clusters create my-cluster \
              --zone us-central1-a \
              --num-nodes 3 \
              --enable-autoscaling --min-nodes=1 --max-nodes=5 \
              --scopes "https://www.googleapis.com/auth/cloud-platform"
        else
          echo "Cluster exists. Proceeding with deployment."
        fi

  # Step 2: Configure kubectl to use the cluster
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a --project kunal-ica1

  # Step 3: Build and deploy using Skaffold
  - name: 'gcr.io/k8s-skaffold/skaffold'
    args:
      - 'run'
      - '--default-repo=gcr.io/kunal-ica1'
      - '--profile=dev'

images:
  - 'gcr.io/kunal-ica1/text-generator:latest'
options:
  logging: CLOUD_LOGGING_ONLY
