apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: text-generator-pipeline
description: Pipeline for deploying the text generator application
serialPipeline:
  stages:
  - targetId: dev
    profiles: []
  - targetId: prod
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev
description: Development environment
gke:
  cluster: projects/kunal-ica1/locations/us-central1-a/clusters/my-cluster
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: Production environment
requireApproval: true
gke:
  cluster: projects/kunal-ica1/locations/us-central1-a/clusters/my-cluster
