apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: smart-hire-pipeline
  serialPipeline:
    stages:
      - name: dev
        targetId: smart-hire-dev
      - name: prod
        targetId: smart-hire-prod
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: smart-hire-dev
  gke:
    cluster: projects/kunal-ica1/locations/us-central1/clusters/your-cluster-name
    location: us-central1
    clusterNamespace: dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: smart-hire-prod
  gke:
    cluster: projects/kunal-ica1/locations/us-central1/clusters/your-cluster-name
    location: us-central1
    clusterNamespace: prod
