steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kunal-ica1/text-generator:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kunal-ica1/text-generator:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'text-generator', '--image', 'gcr.io/kunal-ica1/text-generator:latest', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated', '--quiet']
images:
  - 'gcr.io/kunal-ica1/text-generator:latest'
options:
  logging: CLOUD_LOGGING_ONLY
