apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: smart-hire
build:
  artifacts:
    - image: gcr.io/kunal-ica1/smart-hire
deploy:
  kubectl:
    manifests:
      - kubernetes/deployment.dev.yaml
      - kubernetes/service.yaml
profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - kubernetes/deployment.dev.yaml
          - kubernetes/service.yaml
  - name: prod
    deploy:
      kubectl:
        manifests:
          - kubernetes/deployment.prod.yaml
          - kubernetes/service.yaml
