apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generator-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: text-generator
  template:
    metadata:
      labels:
        app: text-generator
    spec:
      containers:
      - name: text-generator
        image: gcr.io/kunal-ica1/text-generator:latest
        ports:
        - containerPort: 8080
